(define (problem p1)
	(:domain hanoi)
	(:objects k1 k2 k3 k4 k5 x y z)
	(:init
		(on-top k5 x)
		(on-top k4 k5)
		(on-top k3 k4)
		(on-top k2 k3) ; co na czym
		(on-top k1 k2)
		(clear y)
		(clear z)
		(clear k1)
		(smaller k4 k5) ; co mniejsze od czego
		(smaller k3 k5)
		(smaller k2 k5)
		(smaller k1 k5)
		(smaller k3 k4)
		(smaller k2 k4)
		(smaller k1 k4)
		(smaller k2 k3)
		(smaller k1 k3)
		(smaller k1 k2)
		(smaller k5 x)
		(smaller k4 x)
		(smaller k3 x)
		(smaller k2 x)
		(smaller k1 x)
		(smaller k5 y)
		(smaller k4 y)
		(smaller k3 y)
		(smaller k2 y)
		(smaller k1 y)
		(smaller k5 z)
		(smaller k4 z)
		(smaller k3 z)
		(smaller k2 z)
		(smaller k1 z)
	)
	(:goal
		(and
		(on-top k5 z)
		(on-top k4 k5)
		(on-top k3 k4)
		(on-top k2 k3)
		(on-top k1 k2)
		(clear y)
		(clear x)
		(clear k1)
		)
	)
)
